### ISSUE TITLE
Cannot start via controller inputs

### ISSUE THREAD

**Issue by elfbutt** [MiSTer-devel/Arcade-Birdiy_MiSTer#1]
After defining controller buttons, I'm able to press the button I mapped to 1P Start to insert a coin, but it doesn't also start the game. I have to press F1 on a keyboard to begin

**Comment by alanswx** [comment]
I think I forgot to play birdiy with the joystick. I was concentrating on cocktail mode. I will test it and try to push a new version soon. Thank you for the bug report.

**Comment by alanswx** [comment]
Fixed!
